config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories do
    collection do
      get 'search'
    end
    resources :reviews
    resources :chats
  end
root 'stories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :stories
end

app/models/chat.rb
class Chat < ActiveRecord::Base
    belongs_to :story
	belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :story
	belongs_to :user

 validates :story_id, uniqueness: { scope: :user_id, message: "You've already reviewed this story!" }
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews
	has_many :chats

	validates :user_id, presence: true

	

	
	has_attached_file :story_img, :styles => { :story_index => "250x350>", :story_show => "325x475>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :story_img, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :stories
	has_many :reviews
	has_many :chats
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
before_action :find_story
	before_action :find_chat, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@chat = Chat.new
	end

	def create
		@chat = Chat.new(chat_params)
		@chat.story_id = @story.id
		@chat.user_id = current_user.id

		if @chat.save
			redirect_to story_path(@story)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @chat.update(chat_params)
			redirect_to story_path(@story)
		else
			render 'edit'
		end
	end

	def destroy
		@chat.destroy
		redirect_to story_path(@story)
	end

	private

		def chat_params
			params.require(:chat).permit(:comment)
		end

		def find_story
			@story = Story.find(params[:story_id])
		end

		def find_chat
			@chat = Chat.find(params[:id])
		end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_story
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	if current_user 
		@review = Review.where(user_id: current_user.id, story_id: params[:story_id]).first_or_initialize 
    if @review.id.present? 
      render 'edit' 
    end 
	end 
	end

	def create
		@review = Review.new(review_params)
		@review.story_id = @story.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to story_path(@story)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to story_path(@story)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to story_path(@story)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_story
			@story = Story.find(params[:story_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    
    before_action :find_story, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	
	
	def index
		if params[:category].blank?
			@stories = Story.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@stories = Story.where(:category_id => @category_id).order("created_at DESC")
		
		end
		
	end

	def show
		 @reviews =  @story.reviews.order("created_at DESC")
    unless @stories.present?
     @avg_review = 0
    else
     @avg_review = @reviews.average(:rating).present? ? @reviews.average(:rating).round(2) : 0
    end
	end
	
	

	def new
		@story = current_user.stories.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@story = current_user.stories.build(story_params)
		@story.category_id = params[:category_id]

		if @story.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@story.category_id = params[:category_id]
		if @story.update(story_params)
			redirect_to story_path(@story)
		else
			render 'edit'
		end
	end

	def destroy
		@story.destroy
		redirect_to root_path
	end

	private

		def story_params
			params.require(:story).permit(:headline, :summary, :writer, :url, :category_id, :story_img)
		end

		def find_story
			@story = Story.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/chats/_chat.html.erb
<div class="chat">

	<p class="story-chat"><%= chat.comment %></p>


	<% if user_signed_in? %>

		<% if chat.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Edit", edit_story_chat_path(chat.story, chat), class: "btn btn-custom" %>
				<%= link_to "Delete", story_chat_path(chat.story, chat), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

			</div>
		
		<% end %>	

	<% end %>

</div>		

app/views/chats/_form.html.erb
<%= simple_form_for([@story, @story.chats.build]) do |f| %>
	<div id="chat-form">
	
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/chats/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-chat-form">

		<h1>Edit comment</h1>

		<%= simple_form_for([@story, @chat]) do |f| %>
			
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

app/views/chats/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-chat-form">

		<h1>New Comment</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "All Stories", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			<%= form_tag search_stories_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
			<p> 
			<%= text_field_tag :search, params[:search], class: "form-control" %>
			<%= submit_tag "Search", name: nil, class: "btn btn-default" %> 
			</p>
			<% end %>
			

			<ul class="nav navbar-nav navbar-right">

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, stories_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>


				<% if user_signed_in? %>
					<li><%= link_to "Add News Story", new_story_path %></li>
				<% end %>
				
			</ul>

		</div>

	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
		<%= yield %>
	</div>	

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@story, @story.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">

	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>


	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Edit", edit_story_review_path(review.story, review), class: "btn btn-custom" %>
				<%= link_to "Delete", story_review_path(review.story, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

			</div>
		
		<% end %>	

	<% end %>

</div>		

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= simple_form_for([@story, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h1>New Review</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/stories/_form.html.erb
<%= simple_form_for @story, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= f.file_field :story_img %>
	<%= f.input :headline, label: "Headline Title" %>
	<%= f.input :summary %> 
	<%= f.input :writer %>
	<%= f.input :publication %>
	<%= f.input :url %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/stories/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-story-form">

		<h1>Edit Story</h1>

		<%= simple_form_for @story, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :story_img %>
			<%= f.input :headline, label: "Headline Title" %>
	        <%= f.input :summary %>
        	<%= f.input :writer %>
        	<%= f.input :publication %>
	        <%= f.input :url %>
	        <%= f.button :submit, :class => 'btn-custom2' %>
		<% end %>

	</div>

</div>


	

app/views/stories/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
	<h1>Review The News</h1>
	<p>Give your opinion on the quality and truthfulness of news articles and stories. You decide if it really is fake news!</p>
	<p><%= link_to "Sign up to submit a news story for review, rate and comment on a news story", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>
<% else %>
<div class="jumbotron">
	<h1>gubgook. Review The News.</h1>
	<p>scroll down to see the most recent news articles submitted for review</p>

</div>
<% end %>




<h2>All Categories</h2>

<h1 class="current-category"><%= params[:category] %></h1>

<% if @stories.count == 0 %>

	<h1>There are no stories currently in this category</h1>

<% else %>	

	<div class="row">

		<% @stories.each do |story| %>

			<div class="col-md-12">
				<a href="/stories/<%= story.id %>">
					<%= image_tag story.story_img.url(:story_index), class: "story" %>
					<h3><%= story.headline %></h3> 
				</a>
				</div>	
			
			

		<% end %>

	</div>
	
<% end %>

app/views/stories/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-story-form">

		<h1>New Story</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/stories/show.html.erb
<div class="row">

	<div class="col-md-4">

		<%= image_tag @story.story_img.url(:story_show), class: "story-show" %>
	
				<%= link_to "Review this article", new_story_review_path(@story), class: "btn-custom" %>
			</div>
	<div class="col-md-8">

		<div class="story-info">

			<h2 class="news-headline"></h2>
			<h3 class="story-writer"><span>By:</span> <%= @story.writer %></h3>
			<h3 class="story-publication"><span>from:</span> <%= @story.publication %></h3>
			<h2 class="avg-rating">Average Rating</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews">Based on <%= @story.reviews.count %> reviews</span>
			<p class="story-summary"><%= @story.summary %></p>
			<h3 class="story-url"><span>Full story at:</span> <%= @story.url %></h3>
			<p class="uploaded at"><span>submitted for review on:</span><%= @story.created_at.to_formatted_s(:short) %></p>
<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>

	<% if user_signed_in? %>

		<% if @story.user_id == current_user.id %>

			<%= link_to "Edit", edit_story_path(@story), class: "btn btn-custom" %>
			<%= link_to "Delete", story_path(@story), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
			

		<% end %>
		
	<% end %>	

</div>	

	<%= link_to "Add your comment", new_story_chat_path(@story), class: "btn-custom" %>
<div class="row">

	<div class="col-md-8">
		

		<div class="chats">


			<!-- Where the comments will go -->
			<h3>Comments</h3>
		<% if @chats.blank? %>
			<h3>No comments just yet, would you like to be the first!</h3>
			<%= link_to "Add Comment", new_story_chat_path(@story), class: "btn btn-danger" %>
			<% else %>
		
		<%= render @story.chats %>	
<% end %>

		</div>	

	</div>

</div>
		</div>
	</div>


</div>


<div class="row">

	<div class="col-md-4">
			

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h3>Reviews</h3>
		
			<% if @reviews.blank? %>
			<h3>No reviews just yet, would you like to add the first!</h3>
			<%= link_to "Write Review", new_story_review_path(@story), class: "btn btn-danger" %>
			<% else %>
			
			<%= render @story.reviews %>

		    <% end %>


		</div>	

	</div>

</div>



<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>